name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Build e test
        run: |
          cd ${{ matrix.project }}
          yarn build
          yarn test
