name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ${{ matrix.project }}/yarn.lock

      - name: Instalar dependências
        working-directory: ${{ matrix.project }}
        run: yarn install --frozen-lockfile

      - name: Rodar testes
        working-directory: ${{ matrix.project }}
        run: yarn test

      - name: Build do projeto
        working-directory: ${{ matrix.project }}
        run: yarn build
